apiVersion: mesh.cellery.io/v1alpha1
kind: Cell
metadata:
  name: stock-options
  annotations:
    mesh.cellery.io/cell-image-org: cellery-samples
    mesh.cellery.io/cell-image-name: stock-options
    mesh.cellery.io/cell-image-version: 1.0.0
spec:
  gatewayTemplate:
    spec:
      type: MicroGateway
      http:
      - context: stock
        definitions:
        - path: /options
          method: GET
        backend: stock
        global: false
  servicesTemplates:
  - metadata:
      name: stock
    spec:
      replicas: 1
      container:
        image: docker.io/celleryio/sampleapp-stock
        ports:
        - containerPort: 8080
      servicePort: 80
  - metadata:
      name: debug
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/k8s-debug-tools
      servicePort: 80
