[project]
org-name= "celleryio"
version= "0.5.0"

[dependencies]

[platform]
target = "java8"

  [[platform.libraries]]
  module = "cellery"
  path = "./cellery-utils/target/cellery-utils-0.5.0-SNAPSHOT.jar"
