[project]
org-name= "celleryio"
version= "0.6.0"
keywords = ["cellery","microservices","kubernetes"]
repository = "https://github.com/wso2-cellery/sdk"

[dependencies]

[platform]
target = "java8"

  [[platform.libraries]]
  module = "cellery"
  path = "./cellery-utils/target/cellery-utils-0.6.0-SNAPSHOT.jar"
