[project]
org-name= "celleryio"
version= "0.5.0"

[dependencies]

[platform]
target = "java8"

  [[platform.libraries]]
  module = "cellery"
  path = "./cellery-utils/target/cellery-utils-0.4.0.jar"
  artafactId = "cellery-utils"
  version = "0.4.0"
  groupId = "io.cellery"
